
name: Cocos Creator build and test
on: [push, pull_request]

jobs:
  build-deploy:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cocos Creator Build
        run: |
          curl -o CocosCreator_V3.6.2.zip https://download.cocos.com/CocosCreator/v3.6.2/CocosCreator-v3.6.2-mac-102813.zip 
          /usr/bin/unzip -o -q CocosCreator_V3.6.2.zip
          /usr/bin/open ./CocosCreator.app
          chmod 755 build.sh
          ./build.sh 
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web-mobile
          destination_dir: docs 